SELECT USER_ID, NICKNAME, CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2 전체주소, 
        SUBSTR(TLNO,0,3) || '-' || SUBSTR(TLNO,4,4) || '-' || SUBSTR(TLNO,8,4) 전화번호
FROM USED_GOODS_USER 
WHERE USER_ID IN (
                SELECT UU.USER_ID
                FROM USED_GOODS_BOARD UB
                   , USED_GOODS_USER  UU
                WHERE UU.USER_ID = UB.WRITER_ID
                GROUP BY UU.USER_ID
                HAVING COUNT(*) >= 3
)
ORDER BY USER_ID DESC