SELECT FLAVOR
FROM (
    SELECT FH.FLAVOR, (FH.TOTAL_ORDER + JU.TOTAL_ORDER) TOTAL_ORDER
    FROM FIRST_HALF FH
       , (
           SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
           FROM JULY
           GROUP BY FLAVOR
       ) JU
    WHERE JU.FLAVOR = FH.FLAVOR
    ORDER BY TOTAL_ORDER DESC
)
WHERE ROWNUM <= 3