SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM (
    SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD   
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) UB
, USED_GOODS_USER UU
WHERE UB.TOTAL_SALES >= 700000
  AND UU.USER_ID = UB.WRITER_ID
ORDER BY TOTAL_SALES 
;