SELECT UB.TITLE, UB.BOARD_ID, UR.REPLY_ID, UR.WRITER_ID
        , UR.CONTENTS, TO_CHAR(UR.CREATED_DATE, 'YYYY-MM-DD') CREATED_DATE
FROM USED_GOODS_BOARD UB
   , USED_GOODS_REPLY UR
WHERE UR.BOARD_ID = UB.BOARD_ID
  AND TO_CHAR(UB.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY UR.CREATED_DATE, UB.TITLE